apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:3ed65554d08ff52d7cacb39c52dff49f313fd84b483f64cc977d42d028881ee9
  name: jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
