apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:af36671ceffbe834b2d2a4ad89d50ea159e4c4e9d54e7a50582d0bef6be91468
  name: jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
