apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:34cba8edb7422fbf6395e78b4c8ff0e681a07fd9e52f875aa780896e04f7b701
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
