apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:cc54423e294bb69e3e046f0b8d186679e3d1397a28146cfcfa854a2dc07ab8e3
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
