apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:e9750857ae46ca94375511030732a55c59952f74c09b3dd485443ab0fb174fc4
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
