apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:dbb99c62bf9ea175ed9f6eb5b7d44092584e6fcf7fb04605a1b237910c1ffa4f
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
