apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:fb61a4b0e5265a68e877542a8b5e719034e728a5b15460a470ec224d007fdb5e
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
