apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:b1038efe6c896261faef35534acaba2c97470048f01c3f6449a63a450ad4efb5
  name: ghcr.io/jgustie/test-deploy
  newName: ghcr.io/jgustie/such-test-deploy
