name: deploy
on: registry_package
concurrency: development

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump the payload
      run: |
        echo "${{toJSON(github.event)}}"

  publish:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push.outputs.image }}
    steps:
    - name: Install registry package
      run: ${{ github.event.registry_package.package_version.installation_command }}
    - name: Login to GHCR
      id: login
      run: |
        echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
        echo "::set-output name=registry::ghcr.io/${{ github.event.registry_package.namespace }}"
    - name: Push image
      env:
        SOURCE_IMAGE: ${{ github.event.registry_package.package_version.package_url }}
        TARGET_IMAGE: ${{ steps.login.outputs.registry }}/such-${{ github.event.registry_package.name }}
      id: push
      run: |
        docker tag "${SOURCE_IMAGE}" "${TARGET_IMAGE}"
        docker push "${TARGET_IMAGE}"
        echo "::set-output name=image::${TARGET_IMAGE}@${{ github.event.registry_package.package_version.version }}"

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    env:
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git Author
      run: |
        echo "GIT_AUTHOR_NAME=$(curl -s "${{ github.event.sender.url }}" | jq -r '.name')" >> $GITHUB_ENV
        echo "GIT_AUTHOR_EMAIL=${{ github.event.sender.login }}@users.noreply.github.com" >> $GITHUB_ENV
    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/kustomize
    - name: Update image reference
      env:
        SOURCE_IMAGE: ${{ github.event.registry_package.package_version.package_url }}
        TARGET_IMAGE: ${{ needs.publish.outputs.image }}
      run: |
        find applications -path "*/${{ github.event.registry_package.name }}/dev/kustomization.yaml" \
          -execdir kustomize edit set image "${SOURCE_IMAGE%:*}=${TARGET_IMAGE}" \; \
          -execdir git commit -m "Update the '${{ github.event.registry_package.name }}' image reference" -- kustomization.yaml \;
        git push
    - name: Dump kustomize build
      run: |
        kustomize build applications/test-deploy/dev
