name: deploy
on:
  registry_package:
    types:
    - published
    - updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/kustomize
    - name: Dump the payload
      run: |
        echo "${{toJSON(github.event)}}"
        kustomize version
