name: Run Kustomize
on: workflow_dispatch
jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Kustomize
      uses: ./.github/actions/setup-kustomize
      with:
        kustomize-version: 4.2.0
    - name: Run Kustomize
      run: kustomize build applications/test-deploy/dev
